In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [5]:
menu = pd.read_excel("data/데이콘_메뉴_분류.xlsx",sheet_name="분류")
menu.head()

분류        메뉴  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5   볶음류
0  볶음류  대패삼겹숙주볶음         NaN         NaN         NaN         NaN   조림류
1  무침류      봄동나물         NaN         NaN         NaN         NaN  무침류 
2  조림류   콩나물간장조림         NaN         NaN         NaN         NaN    밥류
3   찜류        닭찜         NaN         NaN         NaN         NaN   튀김류
4  무침류    아삭고추무침         NaN         NaN         NaN         NaN   찌개류

In [6]:
ingredient = pd.read_excel("data/데이콘_메뉴_분류.xlsx",sheet_name="재료")
ingredient.head()

재료1  재료2        메뉴  Unnamed: 3 Unnamed: 4
0   육류  채소류  대패삼겹숙주볶음         NaN         곡류
1  채소류  NaN      봄동나물         NaN         두류
2  채소류  NaN   콩나물간장조림         NaN         난류
3   육류  NaN        닭찜         NaN         묵류
4  채소류  NaN    아삭고추무침         NaN        어패류

In [12]:
menu1 = menu[['분류','메뉴']]
ingredient1 = ingredient[['재료1','재료2','메뉴']]

In [13]:
menus = pd.merge(menu1, ingredient1, left_on="메뉴",right_on="메뉴", how="inner")

In [15]:
menus1 = menus[['메뉴','분류','재료1','재료2']]

In [18]:
menus2 = menus1.drop_duplicates(['메뉴','분류','재료1','재료2']).reset_index()
menus2

index        메뉴    분류  재료1  재료2
0         0  대패삼겹숙주볶음   볶음류   육류  채소류
1         1      봄동나물   무침류  채소류  NaN
2         2   콩나물간장조림   조림류  채소류  NaN
3         3        닭찜    찜류   육류  NaN
4         4    아삭고추무침   무침류  채소류  NaN
...     ...       ...   ...  ...  ...
2866   5288     꼬지어묵탕   국탕류  어패류  NaN
2867   5289   고구마치즈구이   구이류   곡류  NaN
2868   5290    나쵸콥샐러드  샐러드류  채소류  NaN
2869   5291   토마토살사소스   소스류  과일류  NaN
2870   5292      단호박죽    죽류  채소류  NaN

[2871 rows x 5 columns]

In [216]:
menu_test = pd.read_csv("data/menu_test.csv")
menu_test.head()

Unnamed: 0         0
0           0    해물우동볶음
1           1  솎음열무나물무침
2           2    매콤해물볶음
3           3     짬뽕수제비
4           4       해물탕

In [222]:
menus3 = pd.merge(menus2,menu_test,left_on="메뉴",right_on="0",how='right')

In [227]:
menus3 = menus3[menus3['메뉴'].isnull()]

In [19]:
menus2.to_csv("data/menu_category_ingredient.csv",encoding="utf-8-sig",index=False)

In [228]:
menus3.to_csv("data/train_category_ingredient.csv",encoding="utf-8-sig",index=False)

# 전처리

In [4]:
menu = pd.read_excel("data/menu_category_ingredient_v3.xlsx")

In [5]:
menu['분류'].unique()

array(['볶음류', '무침류', '조림류', '찜류', '스프류', '밥류', '튀김류', '찌개류', '과일류',
       '샐러드류', '소스류', '면류', '빵과자류', '구이류', '음료류', '국탕류', '회류', '떡류',
       '비빔밥볶음밥류', '죽류', '묵류', '덮밥국밥류', '나물류', '전류', '채소류', '만두류', '김치류',
       '디저트류', '부침류', '유제품류', '해조류', '장아찌류', '견과류', '덥밥국밥류'], dtype=object)

In [6]:
menu['재료1'].unique()

array(['육류', '채소류', '곡류', '어패류', '과일류', '양념 및 장류', '난류', '두류', '김치류',
       '해조류', '유제품류', '만두류'], dtype=object)

In [7]:
menu['재료2'].unique()

array(['채소류', nan, '해조류', '곡류', '김치류', '양념 및 장류', '과일류', '어패류', '난류',
       '유제품류', '육류', '두류', '견과류'], dtype=object)

In [8]:
a = menu['분류'].unique().tolist()
b = menu['재료1'].unique().tolist()
c = menu['재료2'].unique().tolist()
menu_list = list(set(a+b+c))[1:]

In [9]:
len(menu_list)

40

In [67]:
#이상한거 정제
menu['분류'].replace(['덮밥국박류'], '덮밥국밥류',inplace=True)
menu['분류'].replace(['소'], '소스류',inplace=True)
menu['분류'].replace(['기미류'], '김치류',inplace=True)
menu['분류'].replace(['볶움류'], '볶음류',inplace=True)
menu['분류'].replace(['탕류'], '국탕류',inplace=True)
menu['분류'].replace(['면류 '], '면류',inplace=True)
menu['분류'].replace(['구이류 '], '구이류',inplace=True)
menu['분류'].replace(['비빔밥복음밥류'], '비빔밥볶음밥류',inplace=True)
menu['분류'].replace(['국류'], '국탕류',inplace=True)
menu['분류'].replace(['소수류'], '소스류',inplace=True)
menu['분류'].replace(['디저트'], '디저트류',inplace=True)

In [96]:
menu[menu['재료1']=="양념 및 장류"]

index       메뉴   분류      재료1  재료2
17     1116     오미지D  소스류  양념 및 장류  NaN
29     1163       소스  소스류  양념 및 장류  NaN
40     1182    고추간장지  무침류  양념 및 장류  NaN
53     1197     짜장소스  소스류  양념 및 장류  NaN
56     1223        장  소스류  양념 및 장류  NaN
...     ...      ...  ...      ...  ...
2657   5076   청양된장찌개  찌개류  양념 및 장류  NaN
2661   5080     강정소스  소스류  양념 및 장류  NaN
2767   5189       소금  소스류  양념 및 장류  NaN
2774   5196    칠리드레질  소스류  양념 및 장류  NaN
2813   5235  참깨드레싱소스  소스류  양념 및 장류  NaN

[93 rows x 5 columns]

In [72]:
menu.to_csv("data/menu_category_ingredient_v2.csv",encoding="utf-8-sig",index=False)

# 메뉴 split

In [10]:
train = pd.read_csv("data/train_join_v3.csv")
train.head()

test = pd.read_csv("data/test_join_v3.csv")
test.head()

Unnamed: 0  Unnamed: 0.1          일자 요일  본사정원수  본사휴가자수  본사출장자수  \
0           0             0  2021-01-27  수   2983      88     182   
1           1             1  2021-01-28  목   2983     104     212   
2           2             2  2021-01-29  금   2983     270     249   
3           3             3  2021-02-01  월   2924     108     154   
4           4             4  2021-02-02  화   2924      62     186   

   본사시간외근무명령서승인건수  현본사소속재택근무자수  \
0               5        358.0   
1             409        348.0   
2               0        294.0   
3             538        322.0   
4             455        314.0   

                                                조식메뉴  ... 사회적거리두기 1.5단계  \
0  모닝롤/연유버터베이글 우유/주스 계란후라이/찐계란 단호박죽/흑미밥 우거지국 고기완자...  ...           0.0   
1  모닝롤/대만샌드위치 우유/주스 계란후라이/찐계란 누룽지탕/흑미밥 황태국 시래기지짐 ...  ...           0.0   
2  모닝롤/핫케익 우유/주스 계란후라이/찐계란 오곡죽/흑미밥 매생이굴국 고구마순볶음 양...  ...           0.0   
3  모닝롤/촉촉한치즈케익 우유/주스 계란후라이/찐계란 누룽지탕/흑미밥 두부김칫국 새우완...  ...           0.0   
4  모닝롤/토마토샌드 우유/주스 계란후라이/찐계란 채소죽/흑미밥 호박맑은국 오이생채 양...  ...           0.0   

  사회적거리두기 2단계 이상  전국 코로나 확진자 수  경남 코로나 확진자 수  진주 코로나 확진자 수  1단계 누적일수  \
0            1.0         437.0          11.0           2.0         0   
1            1.0         559.0          21.0           7.0         0   
2            1.0         497.0          19.0           5.0         0   
3            1.0         354.0          18.0           0.0         0   
4            1.0         305.0           4.0           0.0         0   

   1.5단계 누적일수  2단계 누적일수  격상 가중치  격하 가중치  
0           0        51     1.0     0.0  
1           0        52     1.0     0.0  
2           0        53     1.0     0.0  
3           0        56     1.0     0.0  
4           0        57     1.0     0.0  

[5 rows x 29 columns]

In [11]:
# Basic text preprocessing

def split_process(x):
    x_ = []
    x = x.split(' ')
    for i in x:
        if '(' in i and ':' in i and ')' in i:
            continue
        if '/' in i:
            x_.extend(i.split('/'))
        elif '*' in i:
            x_.extend(i.split('*'))
        else:
            x_.append(i)
    x_ = list(set(x_))
    x_.remove('')
    return x_

In [97]:
train['조식메뉴_split'] = train['조식메뉴'].apply(lambda x: split_process(x)).to_list()
train['중식메뉴_split'] = train['중식메뉴'].apply(lambda x: split_process(x)).to_list()
train['석식메뉴_split'] = train['석식메뉴'].apply(lambda x: split_process(x)).to_list()

In [12]:
test['조식메뉴_split'] = test['조식메뉴'].apply(lambda x: split_process(x)).to_list()
test['중식메뉴_split'] = test['중식메뉴'].apply(lambda x: split_process(x)).to_list()
test['석식메뉴_split'] = test['석식메뉴'].apply(lambda x: split_process(x)).to_list()

In [13]:
test['석식메뉴_split']

0     [(New)아삭이고추무절임, 버섯햄볶음, 포기김치, 흑미밥, 쇠고기우엉볶음, 얼큰순...
1             [꽃맛살샐러드, 석박지, 오징어무침, 충무김밥, 우동국물, 얼갈이쌈장무침]
2             [카레찜닭, 꼬시래기무침, 포기김치, 흑미밥, 숯불양념꼬지어묵, 물만둣국]
3            [모자반무침, 포기김치, 흑미밥, 동태탕, 돈육꽈리고추장조림, 당면채소무침]
4       [머위된장무침, 백김치, 바지락살국, 흑미밥, 볶은김치, 두부구이, 쇠고기청경채볶음]
5     [빌소세지구이, 구운채소, 양념고추지, 겉절이김치, 오므라이스, 가쓰오장국, 단감치...
6      [세발나물오리엔탈무침, 포기김치, 흑미밥, 돈육두루치기, 계란파국, 감자채파프리카볶음]
7      [국물떡볶이, 온메밀소바, 순대찜, 청경채겉절이, 소금, 추가밥, 포기김치, 유부초밥]
8                  [꼬막채소무침, 청경채찜, 포기김치, 흑미밥, 반반치킨, 냉이국]
9             [단호박두부탕수, 메추리알장조림, 흑미밥, 석박지, 미역국, 매운소불고기]
10        [참치김치찌개, 포기김치, 흑미밥, 오징어굴소스볶음, 건새우무나물, 차돌비빔국수]
11            [쫄면채소무침, 순두부백탕, 얼갈이나물, 수제치킨까스, 포기김치, 흑미밥]
12             [포기김치, 흑미밥, 쇠고기낙지볶음, 카레홍합찜, 쑥갓나물, 손수제비국]
13         [달래양념장, 황태국, 계란후라이, 재래김, 무생채, 찰떡떡갈비조림, 곤드레밥]
14       [양배추숙, 제육볶음, 흑미밥, 겉절이김치, 쌈장, 노가리고추조림, 바지락된장찌개]
15        [콤비네이션피자, 포기김치, 흑미밥, 아귀콩나물찜, 돌나물&된장소스, 버섯들깨탕]
16                  [오이무침, 깐풍육, 동태알탕, 포기김치, 흑미밥, 고사리볶음]
17           [유채나물된장무침, 춘전닭갈비, 뉴욕핫도그, 포기김치, 흑미밥,

In [102]:
lunch_lst = []
lunch_count = []
pref = 0
for i in tqdm(range(1205)):
  try:
    if train['중식계'][i] >= 880:
      pref = 1
    else:
      pref = 0

    lunch_lst.append(train['중식메뉴_split'][i])
    lunch_count.append(pref)
  except:
    pass
print('done')

100%|████████████████████████████████████████████████████████████████████████████| 1205/1205 [00:00<00:00, 8692.25it/s]


done


In [105]:
dinner_lst = []
dinner_count = []
pref_d = 0
for i in tqdm(range(1205)):
  try:
    if train['석식계'][i] > 476:
      pref_d = 1
    else:
      pref_d = 0

    dinner_lst.append(train['석식메뉴_split'][i])
    dinner_count.append(pref_d)
  except:
    pass
# for i in range(len(dinner_lst)):
#   dinner_lst[i] = dinner_lst[i].replace(',', ' ')
print('done')

100%|████████████████████████████████████████████████████████████████████████████| 1205/1205 [00:00<00:00, 7795.01it/s]


done


In [14]:
lunch_lst_test = []
lunch_count_test = []
for i in tqdm(range(50)):
  try:
    lunch_lst_test.append(test['중식메뉴_split'][i])
    lunch_count_test.append(0)
  except:
    pass
# for i in range(len(lunch_lst_test)):
#   lunch_lst_test[i] = lunch_lst_test[i].replace(',', ' ')
print('done')

dinner_lst_test = []
dinner_count_test = []
for i in tqdm(range(50)):
  try:
    dinner_lst_test.append(test['석식메뉴_split'][i])
    dinner_count_test.append(0)
  except:
    pass
# for i in range(len(dinner_lst_test)):
#   dinner_lst_test[i] = dinner_lst_test[i].replace(',', ' ')
print('done')

100%|███████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 16703.72it/s]


done


100%|███████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 25055.58it/s]


done


In [106]:
lunch_df = pd.DataFrame({'중식메뉴':lunch_lst})
dinner_df = pd.DataFrame({'석식메뉴':dinner_lst})

In [15]:
lunch_df_t = pd.DataFrame({'중식메뉴':lunch_lst_test})
dinner_df_t = pd.DataFrame({'석식메뉴':dinner_lst_test})

In [32]:
dinner_df_t

석식메뉴
0   [(New)아삭이고추무절임, 버섯햄볶음, 포기김치, 흑미밥, 쇠고기우엉볶음, 얼큰순...
1           [꽃맛살샐러드, 석박지, 오징어무침, 충무김밥, 우동국물, 얼갈이쌈장무침]
2           [카레찜닭, 꼬시래기무침, 포기김치, 흑미밥, 숯불양념꼬지어묵, 물만둣국]
3          [모자반무침, 포기김치, 흑미밥, 동태탕, 돈육꽈리고추장조림, 당면채소무침]
4     [머위된장무침, 백김치, 바지락살국, 흑미밥, 볶은김치, 두부구이, 쇠고기청경채볶음]
5   [빌소세지구이, 구운채소, 양념고추지, 겉절이김치, 오므라이스, 가쓰오장국, 단감치...
6    [세발나물오리엔탈무침, 포기김치, 흑미밥, 돈육두루치기, 계란파국, 감자채파프리카볶음]
7    [국물떡볶이, 온메밀소바, 순대찜, 청경채겉절이, 소금, 추가밥, 포기김치, 유부초밥]
8                [꼬막채소무침, 청경채찜, 포기김치, 흑미밥, 반반치킨, 냉이국]
9           [단호박두부탕수, 메추리알장조림, 흑미밥, 석박지, 미역국, 매운소불고기]
10      [참치김치찌개, 포기김치, 흑미밥, 오징어굴소스볶음, 건새우무나물, 차돌비빔국수]
11          [쫄면채소무침, 순두부백탕, 얼갈이나물, 수제치킨까스, 포기김치, 흑미밥]
12           [포기김치, 흑미밥, 쇠고기낙지볶음, 카레홍합찜, 쑥갓나물, 손수제비국]
13       [달래양념장, 황태국, 계란후라이, 재래김, 무생채, 찰떡떡갈비조림, 곤드레밥]
14     [양배추숙, 제육볶음, 흑미밥, 겉절이김치, 쌈장, 노가리고추조림, 바지락된장찌개]
15      [콤비네이션피자, 포기김치, 흑미밥, 아귀콩나물찜, 돌나물&된장소스, 버섯들깨탕]
16                [오이무침, 깐풍육, 동태알탕, 포기김치, 흑미밥, 고사리볶음]
17         [유채나물된장무침, 춘전닭갈비, 뉴욕핫도그, 포기김치, 흑미밥, 쇠고기무국]
18           [오복지무침, 애플카레라이스, 소떡소떡, 가지탕수, 포기김치, 팽이장국]
19         [모둠채소전, 씨앗콩자반, 장, 포기김치, 흑미밥, 계란파국, 쭈꾸미불고기]
20   [스팸김치찌개, 브로콜리깨소스무침, 포기김치, 흑미밥, 와사비장, 연근조림, 삼치구이]
21         [솎음열무나물, 해물우동볶음, 날치알계란찜, 포기김치, 흑미밥, 냉이김칫국]
22  [크래미오이보트샐러드, (New)수제오떡탕, 청경채나물, 흑미밥, 겉절이김치, 매운...
23           [고추잡채, 꽃빵, 짬뽕국, 흑미밥, 포기김치, 해초배무침, 쇠고기탕수]
24  [양념장), 라볶이, 포기김치, 미소시루, 상추튀김(모둠튀김, 샐러드김밥, 단무지채무침]
25           [코코뱅, 고구마치즈구이, 포기김치, 흑미밥, 치커리무침, 달래된장찌개]
26      [유채나물무침, 수제두부동그랑땡, 돈육김치볶음, 흑미밥, 포기김치, 맑은콩나물국]
27          [순두부백탕, 쪽파무침, 쇠고기들깨소스무침, 낙지볶음, 포기김치, 흑미밥]
28  [버섯맛살볶음, 얼갈이열무겉절이, 양파장아찌, 양념장, 닭칼국수, 왕만두찜, 볶음고...
29         [뼈해장국, 배추흑임자무침, 매운감자조림, 포기김치, 흑미밥, 가자미유린기]
30          [짜사이볶음, 세발나물무침, 포기김치, 사천탕수육, 해물짜장면, 계란파국]
31  [소면사리, 매콤돈육메추리알장조림, 참나물초장무침, 포기김치, 흑미밥, 사골파국, ...
32   [닭살채소굴소스볶음, 애호박나물, 포기김치, 흑미밥, 쌈장, 김칫국, 알배기,케일숙쌈]
33  [쇠고기규동덮밥, 청경채겉절이, (New)피자핫도그, 포기김치, 연근땅콩조림, 가쓰...
34             [부추전, 부대찌개, 흑미밥, 무생채, 삼치엿장구이, 치커리사과무침]
35         [닭간장조림, 미나리숙주나물, 포기김치, 흑미밥, 순두부찌개, 매콤어묵볶음]
36      [베이컨김치볶음밥, 수제오이피클, 알리오올리오, 포기김치, 계란후라이, 우동국물]
37  [오삼불고기, 강된장, 고들빼기무침, 쇠미역쌈, 맑은버섯국, 흑미밥, 포기김치, 양...
38        [더덕무침, 생선까스, 포기김치, 흑미밥, 타르타르D, 쑥갓무침, 짬뽕수제비]
39  [오복지무침, 차돌된장찌개, 미니팥칼국수, 포기김치, 흑미밥, 적어양념구이, 미트볼...
40     [꽃맛살샐러드, 셀프충무김밥, 오징어어묵무침, 콩나물간장볶음, 포기김치, 미소시루]
41  [빌소세지구이, 구운채소, 추가밥, 애호박새우젓국, 도토리묵채소무침, 포기김치, 오...
42      [납작군만두, 장, 참나물생채무침, 마파두부소스, 흑미밥, 포기김치, 쇠고기무국]
43           [미니우동, 양념고추지, 흑미밥, 열무김치, 미나리전, 치킨까스김치나베]
44           [근대국, 오꼬노미계란말이, 흑미밥, 코다리무조림, 포기김치, 상추무침]
45              [갈치구이, 돈육고추장찌개, 깍두기, 흑미밥, 취나물무침, 김치전]
46    [단무지무침, 추가밥, 메추리알곤약장조림, 포기김치, 수제찹쌀꿔바로우, 생면, 짬뽕]
47     [시금치된장국, 감귤쥬스, 파프리카해초무침, 소떡소떡, 포기김치, 단호박카레라이스]
48          [쑥갓생무침, 어묵매운탕, 김치볶음, 흑미밥, 쇠고기숙주볶음, 채소계란찜]
49      [매운사태조림, 맑은버섯국, 포기김치, 흑미밥, 춘권, 타르타르D, 열무나물무침]

In [33]:
food = list(menu['메뉴'])
food

['대패삼겹숙주볶음',
 '봄동나물',
 '콩나물간장조림',
 '닭찜',
 '아삭고추무침',
 '스프',
 '쌀밥',
 '수제돈가스',
 '수제어묵볶음',
 '차돌박이된장찌개',
 '문어꽈리고추조림',
 '파프리카해초무침',
 '바나나',
 '참치야채비빔밥',
 '브로컬리두부무침',
 '갈치감자조림',
 '양상추샐러드',
 '오미지D',
 '김치국수',
 '생크림와플',
 '김계란말이',
 '푸실리샐러드',
 '커피',
 '버섯육개장',
 '김주먹밥',
 '페스츄리',
 '크래미해초무침',
 '오징어&브로컬리숙회',
 '새우까스',
 '소스',
 '버섯국',
 '매운콩나물무침',
 '사과오이냉국',
 '냉이바지락국',
 '나쵸칩',
 '깐풍연근',
 '국물떡볶이',
 '오리훈제볶음밥',
 '닭죽',
 '새송이버섯볶음',
 '고추간장지',
 '훈제오리떡볶음',
 '열무김치국수',
 '호박잎찌개',
 '시금치프리타타',
 '두부스테이크',
 '포도',
 '볼어묵곤약볶음',
 '비엔나피망볶음',
 '참치주먹밥',
 '모듬소세지버섯구이',
 '야채볶음밥',
 '야채볶음밥',
 '짜장소스',
 '콩나물무침',
 '도토리묵',
 '장',
 '연두부찌개',
 '콘스프',
 '물냉면',
 '돈육볶음',
 '순대국밥',
 '버블샐러드',
 'D오리엔탈D',
 '봄동숙',
 '간장양념',
 '키위드레싱샐러드',
 '쌈장',
 '쌈장',
 '쌈장',
 '쌈장',
 '오이맛살초무침',
 '모듬장조림',
 '해물동그랑땡',
 '삼겹살수육',
 '풋고추',
 '레몬유린기',
 '(New)칠리가지탕수',
 '참나물무침',
 '유부채소겨자냉채',
 '등심찹쌀꿔바로우',
 '옹심이국',
 '생선까스',
 '생선까스',
 '칠리소스',
 '망고드레싱',
 '망고드레싱',
 '조랭이떡국',
 '감자조림',
 '카레감자채볶음',
 '주꾸미브로콜리숙회',
 '야채쫄면',
 '사과오이생채',
 '분홍소세지구이',
 '케찹',
 '비빔메밀국수',
 '버섯매운탕',
 '당면계란만두',
 '냉이콩나물국'

In [34]:
menu_list

['견과류',
 '스프류',
 '덥밥국밥류',
 '해조류',
 '튀김류',
 '묵류',
 '채소류',
 '소스류',
 '구이류',
 '빵과자류',
 '김치류',
 '국탕류',
 '부침류',
 '육류',
 '디저트류',
 '장아찌류',
 '떡류',
 '어패류',
 '죽류',
 '곡류',
 '전류',
 '과일류',
 '찌개류',
 '밥류',
 '음료류',
 '면류',
 '볶음류',
 '비빔밥볶음밥류',
 '회류',
 '덮밥국밥류',
 '유제품류',
 '양념 및 장류',
 '만두류',
 '무침류',
 '조림류',
 '나물류',
 '난류',
 '두류',
 '샐러드류',
 '찜류']

In [48]:
# trigger = np.zeros(40,dtype='int')
# for j,category in enumerate(menu_list):
#     for x in range(1,4):
#         if menu[menu['메뉴']==lunch_df_t.iloc[1][0][0]].iloc[0][0:][x] == category:
#             trigger[j] += 1
menu[menu['메뉴']==lunch_df_t.iloc[1][0][0]].iloc[0][1:]           

분류     구이류
재료1     육류
재료2    NaN
Name: 1783, dtype: object

In [39]:
trigger

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
menu[menu['메뉴']==lunch_df_t.iloc[1][0][0]].iloc[0][1:][0]

'구이류'

In [158]:
lunch_df

중식메뉴
0        [요구르트, 쌀밥, 쇠불고기, 계란찜, 포기김치, 청포묵무침, 잡곡밥, 오징어찌개]
1     [가자미튀김, 모둠소세지구이, 마늘쫑무침, 요구르트, 배추겉절이, 쌀밥, 김치찌개,...
2         [쫄면야채무침, 치킨핑거, 견과류조림, 팽이장국, 요구르트, 포기김치, 카레덮밥]
3       [시금치나물, 쇠고기무국, 요구르트, 쌀밥, 주꾸미볶음, 포기김치, 부추전, 잡곡밥]
4        [돈육씨앗강정, 요구르트, 쌀밥, 우엉잡채, 청경채무침, 포기김치, 떡국, 잡곡밥]
...                                                 ...
1200  [생깻잎지, 오리엔탈D, 수제함박스테이크, 견과류마카로니범벅, 찰현미밥, 쌀밥, 흑...
1201  [냉이된장국, 봄동전, 수수밥, 동파육, 찰현미밥, 무생채, 파인D, 쌀밥, 청경채...
1202  [전주비빔밥, 계란파국, 자몽D, 요거닭, 약고추장, 파프리카해초무침, 포기김치, ...
1203  [봄동겉절이, 달래양념장, 전주식콩나물해장국, 돈육간장불고기, 깐풍연근, 연두부, ...
1204  [찰현미밥, 옥수수콘치즈구이, 가지고추장무침, 요구르트, 쌀밥, 귀리밥, 들깨미역국...

[1205 rows x 1 columns]

In [18]:
dictionary = {string : i for i,string in enumerate(menu_list)}
dictionary

{'견과류': 0,
 '스프류': 1,
 '덥밥국밥류': 2,
 '해조류': 3,
 '튀김류': 4,
 '묵류': 5,
 '채소류': 6,
 '소스류': 7,
 '구이류': 8,
 '빵과자류': 9,
 '김치류': 10,
 '국탕류': 11,
 '부침류': 12,
 '육류': 13,
 '디저트류': 14,
 '장아찌류': 15,
 '떡류': 16,
 '어패류': 17,
 '죽류': 18,
 '곡류': 19,
 '전류': 20,
 '과일류': 21,
 '찌개류': 22,
 '밥류': 23,
 '음료류': 24,
 '면류': 25,
 '볶음류': 26,
 '비빔밥볶음밥류': 27,
 '회류': 28,
 '덮밥국밥류': 29,
 '유제품류': 30,
 '양념 및 장류': 31,
 '만두류': 32,
 '무침류': 33,
 '조림류': 34,
 '나물류': 35,
 '난류': 36,
 '두류': 37,
 '샐러드류': 38,
 '찜류': 39}

In [21]:
if '구이류' in dictionary.keys():
    print(dictionary['구이류'])

8


In [ ]:
#train data
result_lunch = []
result_dinner = []
for k in range(len(lunch_df)): #len(lunch_df)
    trigger = np.zeros(40, dtype='int')
    for i in range(len(lunch_df.iloc[k][0])):
        if lunch_df.iloc[k][0][i] in food:  #메뉴 하나 하나
            #for j,category in enumerate(menu_list):
            for x in range(1,4):
                try:
                    loc = dictionary[menu[menu['메뉴']==lunch_df.iloc[k][0][i]].iloc[0][1:][x]]
                    trigger[loc] += 1
                except:
                    continue
                #printprint(trigger)
    result_lunch.append(trigger)

for k in range(len(dinner_df)): #len(lunch_df)
    trigger = np.zeros(40, dtype='int')
    for i in range(len(dinner_df.iloc[k][0])):
        if dinner_df.iloc[k][0][i] in food:  #메뉴 하나 하나
            #for j,category in enumerate(menu_list):
            for x in range(1,4):
                try:
                    loc = dictionary[menu[menu['메뉴']==dinner_df.iloc[k][0][i]].iloc[0][1:][x]]
                    trigger[loc] += 1
                except:
                    continue
                #printprint(trigger)
    result_dinner.append(trigger)

In [50]:
#test data
result_lunch = []
result_dinner = []
for k in range(len(lunch_df_t)): #len(lunch_df)
    trigger = np.zeros(40, dtype='int')
    for i in range(len(lunch_df_t.iloc[k][0])):
        if lunch_df_t.iloc[k][0][i] in food:  #메뉴 하나 하나
            #for j,category in enumerate(menu_list):
            for x in range(0,3):
                try:
                    loc = dictionary[menu[menu['메뉴']==lunch_df_t.iloc[k][0][i]].iloc[0][1:][x]]
                    trigger[loc] += 1
                except:
                    continue
                #printprint(trigger)
    result_lunch.append(trigger)

for k in range(len(dinner_df_t)): #len(lunch_df)
    trigger = np.zeros(40, dtype='int')
    for i in range(len(dinner_df_t.iloc[k][0])):
        if dinner_df_t.iloc[k][0][i] in food:  #메뉴 하나 하나
            #for j,category in enumerate(menu_list):
            for x in range(0,3):
                try:
                    loc = dictionary[menu[menu['메뉴']==dinner_df_t.iloc[k][0][i]].iloc[0][1:][x]]
                    trigger[loc] += 1
                except:
                    continue
                #printprint(trigger)
    result_dinner.append(trigger)

In [183]:
trigger/trigger.sum()

array([0.04347826, 0.        , 0.        , 0.04347826, 0.        ,
       0.        , 0.17391304, 0.        , 0.04347826, 0.        ,
       0.13043478, 0.08695652, 0.13043478, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.13043478, 0.        , 0.04347826,
       0.        , 0.        , 0.        , 0.04347826, 0.        ,
       0.04347826, 0.        , 0.        , 0.        , 0.04347826,
       0.        , 0.04347826, 0.        , 0.        , 0.        ])

In [51]:
result_dinner

[array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 4, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 4, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 0,

In [52]:
lunch_sort = pd.DataFrame(result_lunch, columns=menu_list)
dinner_sort = pd.DataFrame(result_dinner, columns=menu_list)

In [53]:
dinner_sort

견과류  스프류  덥밥국밥류  해조류  튀김류  묵류  채소류  소스류  구이류  빵과자류  ...  유제품류  양념 및 장류  \
0     0    0      0    0    0   0    2    0    0     0  ...     0        0   
1     0    0      0    0    0   0    2    0    0     0  ...     0        0   
2     0    0      0    0    0   0    1    0    1     0  ...     0        0   
3     0    0      0    1    0   0    1    0    0     0  ...     0        0   
4     0    0      0    0    0   0    1    0    1     0  ...     0        0   
5     0    0      0    0    0   0    4    0    1     0  ...     0        1   
6     0    0      0    0    0   0    2    0    1     0  ...     0        0   
7     0    0      0    0    0   0    1    1    0     0  ...     0        1   
8     0    0      0    0    1   0    3    0    0     0  ...     0        0   
9     0    0      0    1    1   0    1    0    1     0  ...     0        0   
10    0    0      0    0    0   0    0    0    0     0  ...     0        0   
11    0    0      0    0    1   0    1    0    0     0  ...     0        0   
12    0    0      0    0    0   0    1    0    0     0  ...     0        0   
13    0    0      0    2    0   0    3    1    1     0  ...     0        1   
14    0    0      0    0    0   0    1    1    1     0  ...     0        1   
15    0    0      0    0    0   0    3    1    0     1  ...     0        0   
16    0    0      0    0    0   0    2    0    1     0  ...     0        0   
17    0    0      0    0    0   0    1    0    1     1  ...     0        0   
18    0    0      0    0    1   0    3    0    0     0  ...     0        1   
19    0    0      0    0    0   0    1    1    1     0  ...     0        1   
20    0    0      0    0    0   0    2    1    1     0  ...     0        1   
21    0    0      0    0    0   0    2    0    0     0  ...     0        0   
22    0    0      0    0    0   0    2    0    0     0  ...     0        0   
23    0    0      0    1    1   0    1    0    0     1  ...     0        0   
24    0    0      0    0    1   0    3    1    0     0  ...     0        2   
25    0    0      0    0    0   0    2    0    1     0  ...     0        0   
26    0    0      0    0    0   0    2    0    0     0  ...     0        0   
27    0    0      0    0    0   0    1    0    0     0  ...     0        0   
28    0    0      0    0    0   0    3    2    0     0  ...     0        2   
29    0    0      0    0    1   0    1    0    0     0  ...     0        0   
30    0    0      0    0    1   0    1    0    0     0  ...     0        0   
31    0    0      0    0    0   0    2    0    0     0  ...     0        0   
32    0    0      0    0    0   0    4    1    0     0  ...     0        1   
33    0    0      0    0    0   0    2    0    0     1  ...     0        1   
34    0    0      0    0    0   0    3    0    1     0  ...     0        0   
35    0    0      0    0    0   0    1    0    0     0  ...     0        0   
36    0    0      0    0    0   0    2    0    1     0  ...     0        0   
37    0    0      0    1    0   0    5    0    1     0  ...     0        1   
38    0    0      0    0    1   0    2    1    0     0  ...     0        1   
39    0    0      0    0    0   0    2    0    1     0  ...     0        0   
40    0    0      0    0    0   0    3    0    0     0  ...     0        1   
41    0    0      0    0    0   0    6    0    1     0  ...     0        0   
42    0    0      0    0    0   0    2    2    0     0  ...     0        1   
43    0    0      0    0    0   0    2    0    0     0  ...     0        0   
44    0    0      0    0    0   0    2    0    1     0  ...     0        0   
45    0    0      0    0    0   0    1    0    1     0  ...     0        0   
46    0    0      0    0    1   0    1    0    0     0  ...     0        0   
47    0    0      0    1    0   0    3    0    0     0  ...     0        1   
48    0    0      0    0    0   0    2    0    0     0  ...     0        0   
49    0    0      0    0    1   0    1    1    0     0  ...     0        1   

    만두류  무침류  조림류  나물류  난

In [54]:
lunch_df_t

중식메뉴
0   [쌀밥, 대구지리, 오꼬노미계란말이, 흑미밥, 포기김치, 상추무침, 딸기D, 양상추...
1   [오리주물럭, 쌀밥, 오미자D, 우렁된장찌개, 겉절이김치, 수제삼색무쌈, 청양부추전...
2   [쌀밥, 수제돈까스, 파인요거트D, 가자미조림, 동초나물무침, 소스, 포기김치, 흑...
3   [쌀밥, 배추들깨국, 포기김치, 흑미밥, 망고D, 부추고추장무침, 시금치프리타타, ...
4   [쌀밥, 알타리김치, 버섯탕수, 사과푸딩, 오리엔탈D, 부대찌개, 팥밥, 세발나물무...
5   [쌀밥, 감자조림, 미나리나물, 아욱국, 콥샐러드, 포기김치, 흑미밥, 매콤해물볶음...
6   [쌀밥, 고등어김치말이찜, 키위D, 설렁탕, 초장, 석박지, 브로콜리숙회, 차조밥,...
7   [채소전, 쌀밥, 장, 포기김치, 흑미밥, 북엇국, 황도D, 양상추샐러드, 솎음열무...
8   [쌀밥, 돈수육, 감자양파국, 포기김치, 흑미밥, 자몽D, 콩나물파채무침, 씨앗쌈장...
9   [쌀밥, 채소스틱, 겉절이김치, 장각백숙, 참깨D, 적어양념장구이, 쌈장, 도라지오...
10  [단무지락교무침, 그린샐러드, 유니짜장밥, 짬뽕국, 포기김치, 딸기요거트D, 수제찹...
11  [쌀밥, 소갈비찜, 포기김치, 흑미밥, 참나물겉절이, 한식잡채, 블루베리요거트D, ...
12  [수수밥, 수박, 쌀밥, 쌈장, 탕평채, 육개장, 닭살겨자냉채, 깍두기, 오렌지D,...
13  [쌀밥, 알타리김치, 삼겹살고추장구이, 미니쌀국수, 동초나물무침, 흑미밥, 타르타르...
14  [쌀밥, 수원왕갈비통닭, 파인D, 김치어묵탕, 연근깨소스무침, 포기김치, 완두콩밥,...
15  [쌀밥, 유부장국, 마약계란장조림, 딸기D, 포기김치, 흑미밥, 김치전, 해물누룽지...
16  [쌀밥, 감귤D, 마카로니치즈범벅, 흑미밥, 포기김치, 호박고추장찌개, 세발나물무침...
17  [쌀밥, 감자채전, 파스타샐러드, 근대국, 장, 깍두기, 치커리무침, 등갈비김치찜,...
18  [쌀밥, 석류D, 해물탕, 포기김치, 흑미밥, 쇠고기숙주볶음, 맛살계란말이, 물미역...
19  [쌀밥, 키위요거트D, 그린샐러드, 생선까스, 흑미밥, 석박지, 타르타르D, 더덕양...
20  [쌀밥, 베이비크랩강정, 목살스테이크, 이색나물(호박고지,건취나물), 오곡밥, 부럼...
21  [쌀밥, 매운콩나물무침, 치즈불닭, 베이컨감자볶음, 양배추샐러드, 아욱국, 포기김치...
22  [쌀밥, 참나물상추겉절이, 느타리버섯볶음, 망고푸딩, 포기김치, 흑미밥, 동파육, ...
23  [쌀밥, 수수부꾸미, 알타리김치, 옥수수밥, 쑥갓두부무침, 갈치조림, 매운쇠고기샤브...
24  [쌀밥, 미나리나물, 쑥국, 골뱅이채소무침, 포기김치, 흑미밥, 참깨D, 닭다리튀김...
25  [얼갈이된장국, 쌀밥, (New)순대탕수, 깻잎무쌈, 포기김치, 흑미밥, 딸기요거트...
26  [쌀밥, 도라지오이생채, 깍두기, 오렌지D, 매생이전, 갈비탕, 순살닭강정, 차조밥...
27  [양념장, 콥샐러드, 포기김치, 렌치D, 냉이된장국, 봄나물비빔밥, 수제고기육전, ...
28  [쌀밥, 콩가루배추국, 석류D, 귀리밥, 타워함박스테이크, 포기김치, 시금치고추장나...
29  [쌀밥, 쌈채소, 콩소스D, 어묵매운탕, 부추무침, 흑미밥, 겉절이김치, 쌈장, 목...
30  [유부채소겨자냉채, 쌀밥, 비엔나브로콜리볶음, 근대된장국, 흑미밥, 깍두기, 묵은지...
31  [수수밥, 쌀밥, 고등어구이, 대파육개장, 포기김치, 와사비장, 콩샐러드, 건다래순...
32  [제육미나리볶음, 쌀밥, 두부까스, 소스, 흑미밥, 겉절이김치, 매실D, 아삭이고추...
33  [쌀밥, 장각허브오븐구이, 양배추샐러드, 수제오미산적, 포기김치, 청양마요소스, 머...
34  [오이생채, 쌀밥, (New)단호박계란찜, 돈갈비찜, 그린샐러드, 포기김치, 흑미밥...
35  [쌀밥, 쇠고기납작당면볶음, 마카로니콘샐러드, 콩나물불고기, 황태국, 흑미밥, 포기...
36  [쌀밥, 유채나물된장무침, 순남시래기국, 깻잎쌈, 검정콩밥, 겉절이김치, 장어강정,...
37  [비름나물, 쌀밥, 건새우호박채전, 바베큐폭립, 포기김치, 흑미밥, 블루베리요거트D...
38  [쫄면채소무침, 쌀밥, 양배추샐러드, 아욱국, 포기김치, 취나물무침, 짜파치킨, 차...
39  [가지나물, 쌀밥, 풋마늘대무침, 깍두기, 흑미밥, 돈육김치찌개, 흑임자D, 소불고...
40  [요거트푸딩, 쌀밥, 메추리알떡볶이, 차돌박이구이&청경채찜, 그린샐러드, 포기김치,...
41  [쌀밥, 유부장국, 돈수육, 브로콜리땅콩소스무침, 모듬채소, 수제보쌈김치, 키위D,...
42  [버섯초장무침, 쌀밥, 콩가루배추국, 방풍나물, 딸기요거트D, 포기김치, 흑미밥, ...
43  [쌀밥, 통들깨부추무침, 다대기, 발사믹D, 바나나, 채소스틱, 석박지, 순대국밥,...
44  [김말이강정, 쌀밥, 석류D, 꼬시래기무침, 포기김치, 흑미밥, 돈육춘장볶음, 닭개...
45  [오지치즈후라이, 쌀밥, 오미자D, 춘천닭갈비, 가지두반장볶음, 포기김치, 흑미밥,...
46  [순두부백탕, 쌀밥, 돌나물초장무침, 귀리밥, 매콤소갈비찜, 포기김치, 요거트D, ...
47  [쌀밥, 돈육간장불고기, 시저D, 흑미밥, 비빔냉면, 겉절이김치, 냉이국, 양상추샐...
48  [쌀밥, 유채나물무침, 옥수수밥, (New)로제찜닭, 가자미구이, 장, 포기김치, ...
49  [쌀밥, 청포묵, 그린샐러드, 흑미밥, 사골우거지국, 석박지, 망고D, 비름나물고추...

In [55]:
lunch_train = pd.concat([lunch_df,lunch_sort],axis=1)
lunch_train

NameError: name 'lunch_df' is not defined

In [203]:
dinner_train = pd.concat([dinner_df,dinner_sort],axis=1)
dinner_train

석식메뉴  샐러드류  양념 및 장류  나물류  \
0            [두부조림, 쌀밥, 건파래무침, 포기김치, 육개장, 잡곡밥, 자반고등어구이]     0        0    0   
1              [유산슬, 바나나, 어묵국, 포기김치, 아삭고추무침, 양념장, 콩나물밥]     0        1    0   
2          [고기전, 청국장찌개, 새송이버섯볶음, 쌀밥, 황태양념구이, 포기김치, 잡곡밥]     0        1    0   
3              [무피클, 우동, 군고구마, 겨자장, 미니김밥, 포기김치, 멕시칸샐러드]     1        1    0   
4          [감자소세지볶음, 쌀밥, 차돌박이찌개, 닭갈비, 포기김치, 콩나물무침, 잡곡밥]     0        0    0   
...                                                 ...   ...      ...  ...   
1200  [계란후라이, 고들빼기무침, 브로콜리깨소스무침, 맛살튀김, 미니쫄우동, 김치볶음밥,...     0        0    0   
1201      [숙주나물당근무침, 삼치양념구이, 쇠고기무국, 비엔나채소볶음, 흑미밥, 포기김치]     0        0    1   
1202  [수제비국, 참나물무침, 갓김치, 수제맛쵸킹탕수육, 흑미밥, 유부채소겨자냉채, 겉절...     0        0    0   
1203    [장어강정, 깻잎쌈, 생강채, 데리야끼소스, 열무된장국, 흑미밥, 포기김치, 오이선]     0        1    2   
1204   [쑥갓나물, 양파초절임, 깍두기, (New)할라피뇨멸치주먹밥, 수제고기육전, 잔치국수]     0        0    1   

      소스류  두류  찜류  곡류  죽류  국탕류  ...  해조류  과일류  전류  조림류  튀김류  장아찌류  구이류  스프류  \
0       0   1   0   2   0    0  ...    1    0   0    1    0     0    1    0   
1       1   0   0   0   0    1  ...    0    2   0    0    0     0    0    0   
2       0   0   0   2   0    0  ...    0    0   1    0    0     0    1    0   
3       1   0   0   2   0    0  ...    0    0   0    0    0     0    1    0   
4       0   0   0   2   0    0  ...    0    0   0    0    0     0    1    0   
...   ...  ..  ..  ..  ..  ...  ...  ...  ...  ..  ...  ...   ...  ...  ...   
1200    0   0   0   2   0    0  ...    0    0   0    0    1     0    1    0   
1201    0   0   0   1   0    1  ...    0    0   0    0    0     0    1    0   
1202    0   0   0   2   0    1  ...    0    0   0    0    1     0    0    0   
1203    1   0   0   1   0    1  ...    0    0   0    0    1     0    0    0   
1204    0   0   0   1   0    0  ...    0    0   1    0    0     0    0    0   

      덮밥국밥류  떡류  
0         0   0  
1         0   0  
2         0   0  
3         0   0  
4         0   0  
...     ...  ..  
1200      0   0  
1201      0   0  
1202      0   0  
1203      0   0  
1204      0   0  

[1205 rows x 41 columns]

In [56]:
lunch_test = pd.concat([lunch_df_t,lunch_sort],axis=1)
lunch_test

중식메뉴  견과류  스프류  덥밥국밥류  해조류  \
0   [쌀밥, 대구지리, 오꼬노미계란말이, 흑미밥, 포기김치, 상추무침, 딸기D, 양상추...    0    0      0    0   
1   [오리주물럭, 쌀밥, 오미자D, 우렁된장찌개, 겉절이김치, 수제삼색무쌈, 청양부추전...    0    0      0    0   
2   [쌀밥, 수제돈까스, 파인요거트D, 가자미조림, 동초나물무침, 소스, 포기김치, 흑...    0    0      0    0   
3   [쌀밥, 배추들깨국, 포기김치, 흑미밥, 망고D, 부추고추장무침, 시금치프리타타, ...    0    0      0    0   
4   [쌀밥, 알타리김치, 버섯탕수, 사과푸딩, 오리엔탈D, 부대찌개, 팥밥, 세발나물무...    0    0      0    0   
5   [쌀밥, 감자조림, 미나리나물, 아욱국, 콥샐러드, 포기김치, 흑미밥, 매콤해물볶음...    0    0      0    0   
6   [쌀밥, 고등어김치말이찜, 키위D, 설렁탕, 초장, 석박지, 브로콜리숙회, 차조밥,...    0    0      0    0   
7   [채소전, 쌀밥, 장, 포기김치, 흑미밥, 북엇국, 황도D, 양상추샐러드, 솎음열무...    0    0      0    0   
8   [쌀밥, 돈수육, 감자양파국, 포기김치, 흑미밥, 자몽D, 콩나물파채무침, 씨앗쌈장...    0    0      0    0   
9   [쌀밥, 채소스틱, 겉절이김치, 장각백숙, 참깨D, 적어양념장구이, 쌈장, 도라지오...    0    0      0    0   
10  [단무지락교무침, 그린샐러드, 유니짜장밥, 짬뽕국, 포기김치, 딸기요거트D, 수제찹...    0    0      0    0   
11  [쌀밥, 소갈비찜, 포기김치, 흑미밥, 참나물겉절이, 한식잡채, 블루베리요거트D, ...    0    0      0    0   
12  [수수밥, 수박, 쌀밥, 쌈장, 탕평채, 육개장, 닭살겨자냉채, 깍두기, 오렌지D,...    0    0      0    0   
13  [쌀밥, 알타리김치, 삼겹살고추장구이, 미니쌀국수, 동초나물무침, 흑미밥, 타르타르...    0    0      0    0   
14  [쌀밥, 수원왕갈비통닭, 파인D, 김치어묵탕, 연근깨소스무침, 포기김치, 완두콩밥,...    0    0      0    0   
15  [쌀밥, 유부장국, 마약계란장조림, 딸기D, 포기김치, 흑미밥, 김치전, 해물누룽지...    0    0      0    0   
16  [쌀밥, 감귤D, 마카로니치즈범벅, 흑미밥, 포기김치, 호박고추장찌개, 세발나물무침...    0    1      0    0   
17  [쌀밥, 감자채전, 파스타샐러드, 근대국, 장, 깍두기, 치커리무침, 등갈비김치찜,...    0    0      0    0   
18  [쌀밥, 석류D, 해물탕, 포기김치, 흑미밥, 쇠고기숙주볶음, 맛살계란말이, 물미역...    0    0      0    1   
19  [쌀밥, 키위요거트D, 그린샐러드, 생선까스, 흑미밥, 석박지, 타르타르D, 더덕양...    0    0      0    0   
20  [쌀밥, 베이비크랩강정, 목살스테이크, 이색나물(호박고지,건취나물), 오곡밥, 부럼...    1    0      0    0   
21  [쌀밥, 매운콩나물무침, 치즈불닭, 베이컨감자볶음, 양배추샐러드, 아욱국, 포기김치...    0    0      0    0   
22  [쌀밥, 참나물상추겉절이, 느타리버섯볶음, 망고푸딩, 포기김치, 흑미밥, 동파육, ...    0    0      0    1   
23  [쌀밥, 수수부꾸미, 알타리김치, 옥수수밥, 쑥갓두부무침, 갈치조림, 매운쇠고기샤브...    0    0      0    0   
24  [쌀밥, 미나리나물, 쑥국, 골뱅이채소무침, 포기김치, 흑미밥, 참깨D, 닭다리튀김...    0    0      0    0   
25  [얼갈이된장국, 쌀밥, (New)순대탕수, 깻잎무쌈, 포기김치, 흑미밥, 딸기요거트...    0    0      0    0   
26  [쌀밥, 도라지오이생채, 깍두기, 오렌지D, 매생이전, 갈비탕, 순살닭강정, 차조밥...    0    0      0    1   
27  [양념장, 콥샐러드, 포기김치, 렌치D, 냉이된장국, 봄나물비빔밥, 수제고기육전, ...    0    0      0    0   
28  [쌀밥, 콩가루배추국, 석류D, 귀리밥, 타워함박스테이크, 포기김치, 시금치고추장나...    0    0      0    0   
29  [쌀밥, 쌈채소, 콩소스D, 어묵매운탕, 부추무침, 흑미밥, 겉절이김치, 쌈장, 목...    0    0      0    0   
30  [유부채소겨자냉채, 쌀밥, 비엔나브로콜리볶음, 근대된장국, 흑미밥, 깍두기, 묵은지...    0    0      0    0   
31  [수수밥, 쌀밥, 고등어구이, 대파육개장, 포기김치, 와사비장, 콩샐러드, 건다래순...    0    0      0    0   
32  [제육미나리볶음, 쌀밥, 두부까스, 소스, 흑미밥, 겉절이김치, 매실D, 아삭이고추...    0    0      0    0   
33  [쌀밥, 장각허브오븐구이, 양배추샐러드, 수제오미산적, 포기김치, 청양마요소스, 머...    0    0      0    0   
34  [오이생채, 쌀밥, (New)단호박계란찜, 돈갈비찜, 그린샐러드, 포기김치, 흑미밥...    0    0      0    0   
35  [쌀밥, 쇠고기납작당면볶음, 마카로니콘샐러드, 콩나물불고기, 황태국, 흑미밥, 포기...    0    0      0    0   
36  [쌀밥, 유채나물된장무침, 순남시래기국, 깻잎쌈, 검정콩밥, 겉절이김치, 장어강정,...    0    0      0    0   
37  [비름나물, 쌀밥, 건새우호박채전, 바베큐폭립, 포기김치, 흑미밥, 블루베리요거트D...    0    0      0    1   
38  [쫄면채소무침, 쌀밥, 양배추샐러드, 아욱국, 포기김치, 취나물무침, 짜파치킨, 차...    0    0      0    0   
39  [가지나물, 쌀밥, 풋마늘대무침, 깍두기, 흑미밥, 돈육김치찌개, 흑임자D, 소불고...    0    0      0    0   
40  [요거트푸딩, 쌀밥, 메추리알떡볶이, 차돌박이구이&청경채찜, 그린샐러드, 포기김치,...    0    0      0    0   
41  [쌀밥, 유부장국, 돈수육, 브로콜리땅콩소스무침, 모듬채소, 수제보쌈김치, 키위D,...    1    0      0    0   
42  [버섯초장무침, 쌀밥, 콩가루배추국, 방풍나물, 딸기요거트D, 포기김치, 흑미밥, ...    0    0      0    0   
43  [쌀밥, 통들깨부추무침, 다대기, 발사믹D, 바나나, 채소스틱, 석박지, 순대국밥,...    0    0      0    0   
44  [김말이강정, 쌀밥, 석류D, 꼬시래기무침, 포기김치, 흑미밥, 돈육춘장볶음, 닭개...    0    0      0    1   
45  [오지치즈후라이, 쌀밥, 오미자D, 춘천닭갈비, 가지두반장볶음, 포기김치, 흑미밥,...    0    0      0    1   
46  [순두부백탕, 쌀밥, 돌나물초장무침, 귀리밥, 매콤소갈비찜, 포기김치, 요거트D, ...    0    0      0    0   
47  [쌀밥, 돈육간장불고기, 시저D, 흑미밥, 비빔냉면, 겉절이김치, 냉이국, 양상추샐...    0    0      0    0   
48  [쌀밥, 유채나물무침, 옥수수밥, (New)로제찜닭, 가자미구이, 장, 포기김치, ...    0    0      0    0   
49  [쌀밥, 청포묵, 그린샐러드, 흑미밥, 사골우거지국, 석박지, 망고D, 비름나물고추...    0    0      0    0   

    튀김류  묵류  채소류  소

In [57]:
dinner_test = pd.concat([dinner_df_t,dinner_sort],axis=1)
dinner_test

석식메뉴  견과류  스프류  덥밥국밥류  해조류  \
0   [(New)아삭이고추무절임, 버섯햄볶음, 포기김치, 흑미밥, 쇠고기우엉볶음, 얼큰순...    0    0      0    0   
1           [꽃맛살샐러드, 석박지, 오징어무침, 충무김밥, 우동국물, 얼갈이쌈장무침]    0    0      0    0   
2           [카레찜닭, 꼬시래기무침, 포기김치, 흑미밥, 숯불양념꼬지어묵, 물만둣국]    0    0      0    0   
3          [모자반무침, 포기김치, 흑미밥, 동태탕, 돈육꽈리고추장조림, 당면채소무침]    0    0      0    1   
4     [머위된장무침, 백김치, 바지락살국, 흑미밥, 볶은김치, 두부구이, 쇠고기청경채볶음]    0    0      0    0   
5   [빌소세지구이, 구운채소, 양념고추지, 겉절이김치, 오므라이스, 가쓰오장국, 단감치...    0    0      0    0   
6    [세발나물오리엔탈무침, 포기김치, 흑미밥, 돈육두루치기, 계란파국, 감자채파프리카볶음]    0    0      0    0   
7    [국물떡볶이, 온메밀소바, 순대찜, 청경채겉절이, 소금, 추가밥, 포기김치, 유부초밥]    0    0      0    0   
8                [꼬막채소무침, 청경채찜, 포기김치, 흑미밥, 반반치킨, 냉이국]    0    0      0    0   
9           [단호박두부탕수, 메추리알장조림, 흑미밥, 석박지, 미역국, 매운소불고기]    0    0      0    1   
10      [참치김치찌개, 포기김치, 흑미밥, 오징어굴소스볶음, 건새우무나물, 차돌비빔국수]    0    0      0    0   
11          [쫄면채소무침, 순두부백탕, 얼갈이나물, 수제치킨까스, 포기김치, 흑미밥]    0    0      0    0   
12           [포기김치, 흑미밥, 쇠고기낙지볶음, 카레홍합찜, 쑥갓나물, 손수제비국]    0    0      0    0   
13       [달래양념장, 황태국, 계란후라이, 재래김, 무생채, 찰떡떡갈비조림, 곤드레밥]    0    0      0    2   
14     [양배추숙, 제육볶음, 흑미밥, 겉절이김치, 쌈장, 노가리고추조림, 바지락된장찌개]    0    0      0    0   
15      [콤비네이션피자, 포기김치, 흑미밥, 아귀콩나물찜, 돌나물&된장소스, 버섯들깨탕]    0    0      0    0   
16                [오이무침, 깐풍육, 동태알탕, 포기김치, 흑미밥, 고사리볶음]    0    0      0    0   
17         [유채나물된장무침, 춘전닭갈비, 뉴욕핫도그, 포기김치, 흑미밥, 쇠고기무국]    0    0      0    0   
18           [오복지무침, 애플카레라이스, 소떡소떡, 가지탕수, 포기김치, 팽이장국]    0    0      0    0   
19         [모둠채소전, 씨앗콩자반, 장, 포기김치, 흑미밥, 계란파국, 쭈꾸미불고기]    0    0      0    0   
20   [스팸김치찌개, 브로콜리깨소스무침, 포기김치, 흑미밥, 와사비장, 연근조림, 삼치구이]    0    0      0    0   
21         [솎음열무나물, 해물우동볶음, 날치알계란찜, 포기김치, 흑미밥, 냉이김칫국]    0    0      0    0   
22  [크래미오이보트샐러드, (New)수제오떡탕, 청경채나물, 흑미밥, 겉절이김치, 매운...    0    0      0    0   
23           [고추잡채, 꽃빵, 짬뽕국, 흑미밥, 포기김치, 해초배무침, 쇠고기탕수]    0    0      0    1   
24  [양념장), 라볶이, 포기김치, 미소시루, 상추튀김(모둠튀김, 샐러드김밥, 단무지채무침]    0    0      0    0   
25           [코코뱅, 고구마치즈구이, 포기김치, 흑미밥, 치커리무침, 달래된장찌개]    0    0      0    0   
26      [유채나물무침, 수제두부동그랑땡, 돈육김치볶음, 흑미밥, 포기김치, 맑은콩나물국]    0    0      0    0   
27          [순두부백탕, 쪽파무침, 쇠고기들깨소스무침, 낙지볶음, 포기김치, 흑미밥]    0    0      0    0   
28  [버섯맛살볶음, 얼갈이열무겉절이, 양파장아찌, 양념장, 닭칼국수, 왕만두찜, 볶음고...    0    0      0    0   
29         [뼈해장국, 배추흑임자무침, 매운감자조림, 포기김치, 흑미밥, 가자미유린기]    0    0      0    0   
30          [짜사이볶음, 세발나물무침, 포기김치, 사천탕수육, 해물짜장면, 계란파국]    0    0      0    0   
31  [소면사리, 매콤돈육메추리알장조림, 참나물초장무침, 포기김치, 흑미밥, 사골파국, ...    0    0      0    0   
32   [닭살채소굴소스볶음, 애호박나물, 포기김치, 흑미밥, 쌈장, 김칫국, 알배기,케일숙쌈]    0    0      0    0   
33  [쇠고기규동덮밥, 청경채겉절이, (New)피자핫도그, 포기김치, 연근땅콩조림, 가쓰...    0    0      0    0   
34             [부추전, 부대찌개, 흑미밥, 무생채, 삼치엿장구이, 치커리사과무침]    0    0      0    0   
35         [닭간장조림, 미나리숙주나물, 포기김치, 흑미밥, 순두부찌개, 매콤어묵볶음]    0    0      0    0   
36      [베이컨김치볶음밥, 수제오이피클, 알리오올리오, 포기김치, 계란후라이, 우동국물]    0    0      0    0   
37  [오삼불고기, 강된장, 고들빼기무침, 쇠미역쌈, 맑은버섯국, 흑미밥, 포기김치, 양...    0    0      0    1   
38        [더덕무침, 생선까스, 포기김치, 흑미밥, 타르타르D, 쑥갓무침, 짬뽕수제비]    0    0      0    0   
39  [오복지무침, 차돌된장찌개, 미니팥칼국수, 포기김치, 흑미밥, 적어양념구이, 미트볼...    0    0      0    0   
40     [꽃맛살샐러드, 셀프충무김밥, 오징어어묵무침, 콩나물간장볶음, 포기김치, 미소시루]    0    0      0    0   
41  [빌소세지구이, 구운채소, 추가밥, 애호박새우젓국, 도토리묵채소무침, 포기김치, 오...    0    0      0    0   
42      [납작군만두, 장, 참나물생채무침, 마파두부소스, 흑미밥, 포기김치, 쇠고기무국]    0    0      0    0   
43           [미니우동, 양념고추지, 흑미밥, 열무김치, 미나리전, 치킨까스김치나베]    0    0      0    0   
44           [근대국, 오꼬노미계란말이, 흑미밥, 코다리무조림, 포기김치, 상추무침]    0    0      0    0   
45              [갈치구이, 돈육고추장찌개, 깍두기, 흑미밥, 취나물무침, 김치전]    0    0      0    0   
46    [단무지무침, 추가밥, 메추리알곤약장조림, 포기김치, 수제찹쌀꿔바로우, 생면, 짬뽕]    0    0      0    0   
47     [시금치된장국, 감귤쥬스, 파프리카해초무침, 소떡소떡, 포기김치, 단호박카레라이스]    0    0      0    1   
48          [쑥갓생무침, 어묵매운탕, 김치볶음, 흑미밥, 쇠고기숙주볶음, 채소계란찜]    0    0      0    0   
49      [매운사태조림, 맑은버섯국, 포기김치, 흑미밥, 춘권, 타르타르D, 열무나물무침]    0    0      0    0   

    튀김류  묵류  채소류  소

In [190]:
lunch_train.to_csv("data/lunch_train.csv",encoding="utf-8-sig",index=False)

In [205]:
dinner_train.to_csv("data/dinner_train.csv",encoding="utf-8-sig",index=False)

In [58]:
lunch_test.to_csv("data/lunch_test.csv",encoding="utf-8-sig",index=False)

In [59]:
dinner_test.to_csv("data/dinner_test.csv",encoding="utf-8-sig",index=False)