In [101]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [5]:
menu = pd.read_excel("data/데이콘_메뉴_분류.xlsx",sheet_name="분류")
menu.head()

분류        메뉴  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5   볶음류
0  볶음류  대패삼겹숙주볶음         NaN         NaN         NaN         NaN   조림류
1  무침류      봄동나물         NaN         NaN         NaN         NaN  무침류 
2  조림류   콩나물간장조림         NaN         NaN         NaN         NaN    밥류
3   찜류        닭찜         NaN         NaN         NaN         NaN   튀김류
4  무침류    아삭고추무침         NaN         NaN         NaN         NaN   찌개류

In [6]:
ingredient = pd.read_excel("data/데이콘_메뉴_분류.xlsx",sheet_name="재료")
ingredient.head()

재료1  재료2        메뉴  Unnamed: 3 Unnamed: 4
0   육류  채소류  대패삼겹숙주볶음         NaN         곡류
1  채소류  NaN      봄동나물         NaN         두류
2  채소류  NaN   콩나물간장조림         NaN         난류
3   육류  NaN        닭찜         NaN         묵류
4  채소류  NaN    아삭고추무침         NaN        어패류

In [12]:
menu1 = menu[['분류','메뉴']]
ingredient1 = ingredient[['재료1','재료2','메뉴']]

In [13]:
menus = pd.merge(menu1, ingredient1, left_on="메뉴",right_on="메뉴", how="inner")

In [15]:
menus1 = menus[['메뉴','분류','재료1','재료2']]

In [18]:
menus2 = menus1.drop_duplicates(['메뉴','분류','재료1','재료2']).reset_index()
menus2

index        메뉴    분류  재료1  재료2
0         0  대패삼겹숙주볶음   볶음류   육류  채소류
1         1      봄동나물   무침류  채소류  NaN
2         2   콩나물간장조림   조림류  채소류  NaN
3         3        닭찜    찜류   육류  NaN
4         4    아삭고추무침   무침류  채소류  NaN
...     ...       ...   ...  ...  ...
2866   5288     꼬지어묵탕   국탕류  어패류  NaN
2867   5289   고구마치즈구이   구이류   곡류  NaN
2868   5290    나쵸콥샐러드  샐러드류  채소류  NaN
2869   5291   토마토살사소스   소스류  과일류  NaN
2870   5292      단호박죽    죽류  채소류  NaN

[2871 rows x 5 columns]

In [216]:
menu_test = pd.read_csv("data/menu_test.csv")
menu_test.head()

Unnamed: 0         0
0           0    해물우동볶음
1           1  솎음열무나물무침
2           2    매콤해물볶음
3           3     짬뽕수제비
4           4       해물탕

In [222]:
menus3 = pd.merge(menus2,menu_test,left_on="메뉴",right_on="0",how='right')

In [227]:
menus3 = menus3[menus3['메뉴'].isnull()]

In [19]:
menus2.to_csv("data/menu_category_ingredient.csv",encoding="utf-8-sig",index=False)

In [228]:
menus3.to_csv("data/train_category_ingredient.csv",encoding="utf-8-sig",index=False)

# 전처리

In [45]:
menu = pd.read_csv("data/menu_category_ingredient.csv")

In [68]:
menu['분류'].unique()

array(['볶음류', '무침류', '조림류', '찜류', '스프류', '밥류', '튀김류', '찌개류', '과일류',
       '샐러드류', '소스류', '면류', '빵과자류', '구이류', '음료류', '국탕류', '회류', '떡류',
       '비빔밥볶음밥류', '죽류', '묵류', '덮밥국밥류', '나물류', '전류', '채소류', '만두류', '김치류',
       '디저트류', '부침류', '유제품류', '해조류', '장아찌류', '견과류', '덥밥국밥류'], dtype=object)

In [69]:
menu['재료1'].unique()

array(['육류', '채소류', '곡류', '어패류', '과일류', '양념 및 장류', '난류', '두류', '김치류',
       '해조류', '유제품류'], dtype=object)

In [70]:
menu['재료2'].unique()

array(['채소류', nan, '해조류', '곡류', '김치류', '양념 및 장류', '과일류', '어패류', '난류',
       '유제품류', '육류', '두류'], dtype=object)

In [131]:
a = menu['분류'].unique().tolist()
b = menu['재료1'].unique().tolist()
c = menu['재료2'].unique().tolist()
menu_list = list(set(a+b+c))[1:]

In [67]:
#이상한거 정제
menu['분류'].replace(['덮밥국박류'], '덮밥국밥류',inplace=True)
menu['분류'].replace(['소'], '소스류',inplace=True)
menu['분류'].replace(['기미류'], '김치류',inplace=True)
menu['분류'].replace(['볶움류'], '볶음류',inplace=True)
menu['분류'].replace(['탕류'], '국탕류',inplace=True)
menu['분류'].replace(['면류 '], '면류',inplace=True)
menu['분류'].replace(['구이류 '], '구이류',inplace=True)
menu['분류'].replace(['비빔밥복음밥류'], '비빔밥볶음밥류',inplace=True)
menu['분류'].replace(['국류'], '국탕류',inplace=True)
menu['분류'].replace(['소수류'], '소스류',inplace=True)
menu['분류'].replace(['디저트'], '디저트류',inplace=True)

In [96]:
menu[menu['재료1']=="양념 및 장류"]

index       메뉴   분류      재료1  재료2
17     1116     오미지D  소스류  양념 및 장류  NaN
29     1163       소스  소스류  양념 및 장류  NaN
40     1182    고추간장지  무침류  양념 및 장류  NaN
53     1197     짜장소스  소스류  양념 및 장류  NaN
56     1223        장  소스류  양념 및 장류  NaN
...     ...      ...  ...      ...  ...
2657   5076   청양된장찌개  찌개류  양념 및 장류  NaN
2661   5080     강정소스  소스류  양념 및 장류  NaN
2767   5189       소금  소스류  양념 및 장류  NaN
2774   5196    칠리드레질  소스류  양념 및 장류  NaN
2813   5235  참깨드레싱소스  소스류  양념 및 장류  NaN

[93 rows x 5 columns]

In [72]:
menu.to_csv("data/menu_category_ingredient_v2.csv",encoding="utf-8-sig",index=False)

# 메뉴 split

In [208]:
train = pd.read_csv("data/train_join_v3.csv")
train.head()

test = pd.read_csv("data/test_join_v3.csv")
test.head()

Unnamed: 0  Unnamed: 0.1          일자 요일  본사정원수  본사휴가자수  본사출장자수  \
0           0             0  2021-01-27  수   2983      88     182   
1           1             1  2021-01-28  목   2983     104     212   
2           2             2  2021-01-29  금   2983     270     249   
3           3             3  2021-02-01  월   2924     108     154   
4           4             4  2021-02-02  화   2924      62     186   

   본사시간외근무명령서승인건수  현본사소속재택근무자수  \
0               5        358.0   
1             409        348.0   
2               0        294.0   
3             538        322.0   
4             455        314.0   

                                                조식메뉴  ... 사회적거리두기 1.5단계  \
0  모닝롤/연유버터베이글 우유/주스 계란후라이/찐계란 단호박죽/흑미밥 우거지국 고기완자...  ...           0.0   
1  모닝롤/대만샌드위치 우유/주스 계란후라이/찐계란 누룽지탕/흑미밥 황태국 시래기지짐 ...  ...           0.0   
2  모닝롤/핫케익 우유/주스 계란후라이/찐계란 오곡죽/흑미밥 매생이굴국 고구마순볶음 양...  ...           0.0   
3  모닝롤/촉촉한치즈케익 우유/주스 계란후라이/찐계란 누룽지탕/흑미밥 두부김칫국 새우완...  ...           0.0   
4  모닝롤/토마토샌드 우유/주스 계란후라이/찐계란 채소죽/흑미밥 호박맑은국 오이생채 양...  ...           0.0   

  사회적거리두기 2단계 이상  전국 코로나 확진자 수  경남 코로나 확진자 수  진주 코로나 확진자 수  1단계 누적일수  \
0            1.0         437.0          11.0           2.0         0   
1            1.0         559.0          21.0           7.0         0   
2            1.0         497.0          19.0           5.0         0   
3            1.0         354.0          18.0           0.0         0   
4            1.0         305.0           4.0           0.0         0   

   1.5단계 누적일수  2단계 누적일수  격상 가중치  격하 가중치  
0           0        51     1.0     0.0  
1           0        52     1.0     0.0  
2           0        53     1.0     0.0  
3           0        56     1.0     0.0  
4           0        57     1.0     0.0  

[5 rows x 29 columns]

In [207]:
# Basic text preprocessing

def split_process(x):
    x_ = []
    x = x.split(' ')
    for i in x:
        if '(' in i and ':' in i and ')' in i:
            continue
        if '/' in i:
            x_.extend(i.split('/'))
        elif '*' in i:
            x_.extend(i.split('*'))
        else:
            x_.append(i)
    x_ = list(set(x_))
    x_.remove('')
    return x_

In [97]:
train['조식메뉴_split'] = train['조식메뉴'].apply(lambda x: split_process(x)).to_list()
train['중식메뉴_split'] = train['중식메뉴'].apply(lambda x: split_process(x)).to_list()
train['석식메뉴_split'] = train['석식메뉴'].apply(lambda x: split_process(x)).to_list()

In [210]:
test['조식메뉴_split'] = test['조식메뉴'].apply(lambda x: split_process(x)).to_list()
test['중식메뉴_split'] = test['중식메뉴'].apply(lambda x: split_process(x)).to_list()
test['석식메뉴_split'] = test['석식메뉴'].apply(lambda x: split_process(x)).to_list()

In [99]:
train['석식메뉴_split']

0              [두부조림, 쌀밥, 건파래무침, 포기김치, 육개장, 잡곡밥, 자반고등어구이]
1                [유산슬, 바나나, 어묵국, 포기김치, 아삭고추무침, 양념장, 콩나물밥]
2            [고기전, 청국장찌개, 새송이버섯볶음, 쌀밥, 황태양념구이, 포기김치, 잡곡밥]
3                [무피클, 우동, 군고구마, 겨자장, 미니김밥, 포기김치, 멕시칸샐러드]
4            [감자소세지볶음, 쌀밥, 차돌박이찌개, 닭갈비, 포기김치, 콩나물무침, 잡곡밥]
                              ...                        
1200    [계란후라이, 고들빼기무침, 브로콜리깨소스무침, 맛살튀김, 미니쫄우동, 김치볶음밥,...
1201        [숙주나물당근무침, 삼치양념구이, 쇠고기무국, 비엔나채소볶음, 흑미밥, 포기김치]
1202    [수제비국, 참나물무침, 갓김치, 수제맛쵸킹탕수육, 흑미밥, 유부채소겨자냉채, 겉절...
1203      [장어강정, 깻잎쌈, 생강채, 데리야끼소스, 열무된장국, 흑미밥, 포기김치, 오이선]
1204     [쑥갓나물, 양파초절임, 깍두기, (New)할라피뇨멸치주먹밥, 수제고기육전, 잔치국수]
Name: 석식메뉴_split, Length: 1205, dtype: object

In [102]:
lunch_lst = []
lunch_count = []
pref = 0
for i in tqdm(range(1205)):
  try:
    if train['중식계'][i] >= 880:
      pref = 1
    else:
      pref = 0

    lunch_lst.append(train['중식메뉴_split'][i])
    lunch_count.append(pref)
  except:
    pass
print('done')

100%|████████████████████████████████████████████████████████████████████████████| 1205/1205 [00:00<00:00, 8692.25it/s]


done


In [105]:
dinner_lst = []
dinner_count = []
pref_d = 0
for i in tqdm(range(1205)):
  try:
    if train['석식계'][i] > 476:
      pref_d = 1
    else:
      pref_d = 0

    dinner_lst.append(train['석식메뉴_split'][i])
    dinner_count.append(pref_d)
  except:
    pass
# for i in range(len(dinner_lst)):
#   dinner_lst[i] = dinner_lst[i].replace(',', ' ')
print('done')

100%|████████████████████████████████████████████████████████████████████████████| 1205/1205 [00:00<00:00, 7795.01it/s]


done


In [211]:
lunch_lst_test = []
lunch_count_test = []
for i in tqdm(range(50)):
  try:
    lunch_lst_test.append(test['중식메뉴_split'][i])
    lunch_count_test.append(0)
  except:
    pass
# for i in range(len(lunch_lst_test)):
#   lunch_lst_test[i] = lunch_lst_test[i].replace(',', ' ')
print('done')

dinner_lst_test = []
dinner_count_test = []
for i in tqdm(range(50)):
  try:
    dinner_lst_test.append(test['석식메뉴_split'][i])
    dinner_count_test.append(0)
  except:
    pass
# for i in range(len(dinner_lst_test)):
#   dinner_lst_test[i] = dinner_lst_test[i].replace(',', ' ')
print('done')






100%|███████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 16707.71it/s]


done







100%|███████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 25082.55it/s]


done


In [106]:
lunch_df = pd.DataFrame({'중식메뉴':lunch_lst})
dinner_df = pd.DataFrame({'석식메뉴':dinner_lst})

In [212]:
lunch_df_t = pd.DataFrame({'중식메뉴':lunch_lst_test})
dinner_df_t = pd.DataFrame({'석식메뉴':dinner_lst_test})

In [213]:
lunch_df_t

중식메뉴
0   [대구지리, 매운돈갈비찜, 찰현미밥, 쌀밥, 오꼬노미계란말이, 딸기D, 흑미밥, 포...
1   [겉절이김치, 보리밥, 오미자D, 양상추샐러드, 찰현미밥, 쌀밥, 우렁된장찌개, 수...
2   [수제돈까스, 가자미조림, 팽이장국, 찰현미밥, 쌀밥, 동초나물무침, 흑미밥, 소스...
3   [부추고추장무침, 시금치프리타타, 오리대패불고기, 찰현미밥, 망고D, 배추들깨국, ...
4   [버섯탕수, 닭살데리야끼조림, 오리엔탈D, 찰현미밥, 알타리김치, 쌀밥, 팥밥, 사...
5   [감자조림, 매콤해물볶음, 미나리나물, 찰현미밥, 쌀밥, 흑미밥, 포기김치, 렌치D...
6   [차조밥, 찰현미밥, 석박지, 쌀밥, 고등어김치말이찜, 초장, 설렁탕, 키위D, 양...
7   [채소전, 찰현미밥, 쌀밥, 북엇국, 솎음열무나물무침, 장, 황도D, 흑미밥, 닭볶...
8   [자몽D, 돈수육, 찰현미밥, 씨앗쌈장, 쌀밥, 매콤어묵볶음, 흑미밥, 감자양파국,...
9   [적어양념장구이, 참깨D, 양상추샐러드, 찰현미밥, 쌈장, 기장밥, 쌀밥, 채소스틱...
10  [수제찹쌀꿔바로우, 유니짜장밥, 계란후라이, 그린샐러드, 단무지락교무침, 딸기요거트...
11  [참나물겉절이, 찰현미밥, 쌀밥, 한식잡채, 블루베리요거트D, 흑미밥, 소갈비찜, ...
12  [탕평채, 닭살겨자냉채, 수수밥, 깍두기, 찰현미밥, 쌈장, 양상추샐러드, 쌀밥, ...
13  [미니쌀국수, 오리엔탈D, 찰현미밥, 쌀밥, 동초나물무침, 삼겹살고추장구이, 스프링...
14  [연근깨소스무침, 두부양념조림, 찰현미밥, 완두콩밥, 파인D, 쌀밥, 포기김치, 김...
15  [해물누룽지탕, 마약계란장조림, 김치전, 찰현미밥, 쌀밥, 딸기D, 흑미밥, 포기김...
16  [호박고추장찌개, 안동찜닭, 마카로니치즈범벅, 감귤D, 찰현미밥, 요구르트, 쌀밥,...
17  [파스타샐러드, 치커리무침, 보리밥, 깍두기, 찰현미밥, 감자채전, 쌀밥, 장, 근...
18  [쇠고기숙주볶음, 맛살계란말이, 찰현미밥, 석류D, 해물탕, 쌀밥, 물미역초고추장무...
19  [생선까스, 더덕양념구이, 찰현미밥, 그린샐러드, 키위요거트D, 석박지, 쌀밥, 방...
20  [목살스테이크, 오곡밥, 찰현미밥, 망고D, 부럼, 쌀밥, 베이비크랩강정, 포기김치...
21  [찰현미밥, 매운콩나물무침, 쌀밥, 베이컨감자볶음, 흑미밥, 치즈불닭, 포기김치, ...
22  [찰현미밥, 동파육, 느타리버섯볶음, 쌀밥, 참나물상추겉절이, 망고푸딩, 블루베리요...
23  [자몽D, 찰현미밥, 옥수수밥, 쌀밥, 매운쇠고기샤브샤브국, 쑥갓두부무침, 갈치조림...
24  [닭다리튀김, 참깨D, 골뱅이채소무침, 양상추샐러드, 미나리나물, 찰현미밥, 쌀밥,...
25  [찰현미밥, 얼갈이된장국, 쌀밥, (New)순대탕수, 오리불고기, 딸기요거트D, 흑...
26  [차조밥, 도라지오이생채, 깍두기, 찰현미밥, 오렌지D, 갈비탕, 매생이전, 쌀밥,...
27  [냉이된장국, 콥샐러드, 도토리묵, 렌치D, 봄나물비빔밥, 포기김치, 쥬시쿨, 수제...
28  [타워함박스테이크, 찰현미밥, 석류D, 시금치고추장나물무침, 쌀밥, 귀리밥, 콩가루...
29  [부추무침, 양상추샐러드, 콩소스D, 찰현미밥, 쌈장, 쌈채소, 쌀밥, 어묵매운탕,...
30  [묵은지닭찜, 근대된장국, 깍두기, 찰현미밥, 요구르트, 망고D, 쌀밥, 비엔나브로...
31  [와사비장, 어묵잡채, 수수밥, 찰현미밥, 건다래순볶음, 쌀밥, 대파육개장, 콩샐러...
32  [두부까스, 양상추샐러드, 찰현미밥, 아삭이고추된장무침, 쌀밥, 제육미나리볶음, 물...
33  [수제오미산적, 머위나물, 찰현미밥, 장각허브오븐구이, 기장밥, 쌀밥, 열무된장국,...
34  [오이생채, 돈갈비찜, 찰현미밥, 버섯매운탕, 그린샐러드, 쌀밥, 흑미밥, (New...
35  [콩나물불고기, 쇠고기납작당면볶음, 찰현미밥, 황태국, 삼색유자청무침, 쌀밥, 마카...
36  [장어강정, 깻잎쌈, 양상추샐러드, 찰현미밥, 유채나물된장무침, 요구르트, 검정콩밥...
37  [비름나물, 미역국, 찰현미밥, 건새우호박채전, 쌀밥, 블루베리요거트D, 흑미밥, ...
38  [차조밥, 찰현미밥, 쌀밥, 포기김치, 사우전D, 취나물무침, 양배추샐러드, 아욱국...
39  [돈육김치찌개, 풋마늘대무침, 가지나물, 찰현미밥, 깍두기, 쌀밥, 소불고기, 흑임...
40  [동태매운탕, 참깨D, 요거트푸딩, 차돌박이구이&청경채찜, 찰현미밥, 그린샐러드, ...
41  [수제보쌈김치, 돈수육, 모듬채소, 찰현미밥, 쌈장, 완두콩밥, 쌀밥, 브로콜리땅콩...
42  [찰현미밥, 쌀밥, 콩가루배추국, 방풍나물, 딸기요거트D, 허니순살치킨, 흑미밥, ...
43  [발사믹D, 보리밥, 바나나, 다대기, 해물동그랑땡채소볶음, 양상추샐러드, 찰현미밥...
44  [닭개장, 돈육춘장볶음, 찰현미밥, 석류D, 쌀밥, 흑미밥, 포기김치, 꼬시래기무침...
45  [오지치즈후라이, 가지두반장볶음, 오미자D, 찰현미밥, 춘천닭갈비, 쌀밥, 흑미밥,...
46  [순두부백탕, 돌나물초장무침, 깻잎완자전, 요거트D, 찰현미밥, 쌀밥, 귀리밥, 매...
47  [돈육간장불고기, 양상추샐러드, 찰현미밥, 오이나물볶음, 쌀밥, 비빔냉면, 시저D,...
48  [자몽D, 양상추샐러드, 찰현미밥, 옥수수밥, (New)로제찜닭, 쌀밥, 장, 유채...
49  [사골우거지국, 해물누룽지탕, 양념간장, 찰현미밥, 청포묵, 그린샐러드, 망고D, ...

In [112]:
food = list(menu['메뉴'])
food

['대패삼겹숙주볶음',
 '봄동나물',
 '콩나물간장조림',
 '닭찜',
 '아삭고추무침',
 '스프',
 '쌀밥',
 '수제돈가스',
 '수제어묵볶음',
 '차돌박이된장찌개',
 '문어꽈리고추조림',
 '파프리카해초무침',
 '바나나',
 '참치야채비빔밥',
 '브로컬리두부무침',
 '갈치감자조림',
 '양상추샐러드',
 '오미지D',
 '김치국수',
 '생크림와플',
 '김계란말이',
 '푸실리샐러드',
 '커피',
 '버섯육개장',
 '김주먹밥',
 '페스츄리',
 '크래미해초무침',
 '오징어&브로컬리숙회',
 '새우까스',
 '소스',
 '버섯국',
 '매운콩나물무침',
 '사과오이냉국',
 '냉이바지락국',
 '나쵸칩',
 '깐풍연근',
 '국물떡볶이',
 '오리훈제볶음밥',
 '닭죽',
 '새송이버섯볶음',
 '고추간장지',
 '훈제오리떡볶음',
 '열무김치국수',
 '호박잎찌개',
 '시금치프리타타',
 '두부스테이크',
 '포도',
 '볼어묵곤약볶음',
 '비엔나피망볶음',
 '참치주먹밥',
 '모듬소세지버섯구이',
 '야채볶음밥',
 '야채볶음밥',
 '짜장소스',
 '콩나물무침',
 '도토리묵',
 '장',
 '연두부찌개',
 '콘스프',
 '물냉면',
 '돈육볶음',
 '순대국밥',
 '버블샐러드',
 'D오리엔탈D',
 '봄동숙',
 '간장양념',
 '키위드레싱샐러드',
 '쌈장',
 '쌈장',
 '쌈장',
 '쌈장',
 '오이맛살초무침',
 '모듬장조림',
 '해물동그랑땡',
 '삼겹살수육',
 '풋고추',
 '레몬유린기',
 '(New)칠리가지탕수',
 '참나물무침',
 '유부채소겨자냉채',
 '등심찹쌀꿔바로우',
 '옹심이국',
 '생선까스',
 '생선까스',
 '칠리소스',
 '망고드레싱',
 '망고드레싱',
 '조랭이떡국',
 '감자조림',
 '카레감자채볶음',
 '주꾸미브로콜리숙회',
 '야채쫄면',
 '사과오이생채',
 '분홍소세지구이',
 '케찹',
 '비빔메밀국수',
 '버섯매운탕',
 '당면계란만두',
 '냉이콩나물국'

In [132]:
menu_list

['샐러드류',
 '양념 및 장류',
 '나물류',
 '소스류',
 '두류',
 '찜류',
 '곡류',
 '죽류',
 '국탕류',
 '볶음류',
 '유제품류',
 '김치류',
 '밥류',
 '묵류',
 '만두류',
 '견과류',
 '비빔밥볶음밥류',
 '음료류',
 '회류',
 '부침류',
 '덥밥국밥류',
 '빵과자류',
 '채소류',
 '면류',
 '육류',
 '난류',
 '어패류',
 '디저트류',
 '무침류',
 '찌개류',
 '해조류',
 '과일류',
 '전류',
 '조림류',
 '튀김류',
 '장아찌류',
 '구이류',
 '스프류',
 '덮밥국밥류',
 '떡류']

In [152]:
trigger = np.zeros(40,dtype='int')
for j,category in enumerate(menu_list):
    for x in range(1,4):
        if menu[menu['메뉴']==lunch_df.iloc[1][0][0]].iloc[0][1:][x] == category:
            trigger[j] += 1

In [153]:
trigger

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [148]:
menu[menu['메뉴']==lunch_df.iloc[1][0][0]].iloc[0][1:][1]

'튀김류'

In [158]:
lunch_df

중식메뉴
0        [요구르트, 쌀밥, 쇠불고기, 계란찜, 포기김치, 청포묵무침, 잡곡밥, 오징어찌개]
1     [가자미튀김, 모둠소세지구이, 마늘쫑무침, 요구르트, 배추겉절이, 쌀밥, 김치찌개,...
2         [쫄면야채무침, 치킨핑거, 견과류조림, 팽이장국, 요구르트, 포기김치, 카레덮밥]
3       [시금치나물, 쇠고기무국, 요구르트, 쌀밥, 주꾸미볶음, 포기김치, 부추전, 잡곡밥]
4        [돈육씨앗강정, 요구르트, 쌀밥, 우엉잡채, 청경채무침, 포기김치, 떡국, 잡곡밥]
...                                                 ...
1200  [생깻잎지, 오리엔탈D, 수제함박스테이크, 견과류마카로니범벅, 찰현미밥, 쌀밥, 흑...
1201  [냉이된장국, 봄동전, 수수밥, 동파육, 찰현미밥, 무생채, 파인D, 쌀밥, 청경채...
1202  [전주비빔밥, 계란파국, 자몽D, 요거닭, 약고추장, 파프리카해초무침, 포기김치, ...
1203  [봄동겉절이, 달래양념장, 전주식콩나물해장국, 돈육간장불고기, 깐풍연근, 연두부, ...
1204  [찰현미밥, 옥수수콘치즈구이, 가지고추장무침, 요구르트, 쌀밥, 귀리밥, 들깨미역국...

[1205 rows x 1 columns]

In [174]:
dictionary = {string : i for i,string in enumerate(menu_list)}
dictionary

{'샐러드류': 0,
 '양념 및 장류': 1,
 '나물류': 2,
 '소스류': 3,
 '두류': 4,
 '찜류': 5,
 '곡류': 6,
 '죽류': 7,
 '국탕류': 8,
 '볶음류': 9,
 '유제품류': 10,
 '김치류': 11,
 '밥류': 12,
 '묵류': 13,
 '만두류': 14,
 '견과류': 15,
 '비빔밥볶음밥류': 16,
 '음료류': 17,
 '회류': 18,
 '부침류': 19,
 '덥밥국밥류': 20,
 '빵과자류': 21,
 '채소류': 22,
 '면류': 23,
 '육류': 24,
 '난류': 25,
 '어패류': 26,
 '디저트류': 27,
 '무침류': 28,
 '찌개류': 29,
 '해조류': 30,
 '과일류': 31,
 '전류': 32,
 '조림류': 33,
 '튀김류': 34,
 '장아찌류': 35,
 '구이류': 36,
 '스프류': 37,
 '덮밥국밥류': 38,
 '떡류': 39}

In [178]:
if '구이류' in dictionary.keys():
    print(dictionary['구이류'])

36


In [199]:
result_lunch = []
result_dinner = []
# for k in range(len(lunch_df)): #len(lunch_df)
#     trigger = np.zeros(40, dtype='int')
#     for i in range(len(lunch_df.iloc[k][0])):
#         if lunch_df.iloc[k][0][i] in food:  #메뉴 하나 하나
#             #for j,category in enumerate(menu_list):
#             for x in range(1,4):
#                 try:
#                     loc = dictionary[menu[menu['메뉴']==lunch_df.iloc[k][0][i]].iloc[0][1:][x]]
#                     trigger[loc] += 1
#                 except:
#                     continue
#                 #printprint(trigger)
#     result_lunch.append(trigger)

for k in range(len(dinner_df)): #len(lunch_df)
    trigger = np.zeros(40, dtype='int')
    for i in range(len(dinner_df.iloc[k][0])):
        if dinner_df.iloc[k][0][i] in food:  #메뉴 하나 하나
            #for j,category in enumerate(menu_list):
            for x in range(1,4):
                try:
                    loc = dictionary[menu[menu['메뉴']==dinner_df.iloc[k][0][i]].iloc[0][1:][x]]
                    trigger[loc] += 1
                except:
                    continue
                #printprint(trigger)
    result_dinner.append(trigger)

In [183]:
trigger/trigger.sum()

array([0.04347826, 0.        , 0.        , 0.04347826, 0.        ,
       0.        , 0.17391304, 0.        , 0.04347826, 0.        ,
       0.13043478, 0.08695652, 0.13043478, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.13043478, 0.        , 0.04347826,
       0.        , 0.        , 0.        , 0.04347826, 0.        ,
       0.04347826, 0.        , 0.        , 0.        , 0.04347826,
       0.        , 0.04347826, 0.        , 0.        , 0.        ])

In [200]:
result_dinner

[array([0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        4, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 1, 2, 0, 1,

In [201]:
lunch_sort = pd.DataFrame(result_lunch, columns=menu_list)
dinner_sort = pd.DataFrame(result_dinner, columns=menu_list)

In [202]:
dinner_sort

샐러드류  양념 및 장류  나물류  소스류  두류  찜류  곡류  죽류  국탕류  볶음류  ...  해조류  과일류  전류  \
0        0        0    0    0   1   0   2   0    0    0  ...    1    0   0   
1        0        1    0    1   0   0   0   0    1    1  ...    0    2   0   
2        0        1    0    0   0   0   2   0    0    1  ...    0    0   1   
3        1        1    0    1   0   0   2   0    0    0  ...    0    0   0   
4        0        0    0    0   0   0   2   0    0    1  ...    0    0   0   
...    ...      ...  ...  ...  ..  ..  ..  ..  ...  ...  ...  ...  ...  ..   
1200     0        0    0    0   0   0   2   0    0    0  ...    0    0   0   
1201     0        0    1    0   0   0   1   0    1    1  ...    0    0   0   
1202     0        0    0    0   0   0   2   0    1    0  ...    0    0   0   
1203     0        1    2    1   0   0   1   0    1    0  ...    0    0   0   
1204     0        0    1    0   0   0   1   0    0    0  ...    0    0   1   

      조림류  튀김류  장아찌류  구이류  스프류  덮밥국밥류  떡류  
0       1    0     0    1    0      0   0  
1       0    0     0    0    0      0   0  
2       0    0     0    1    0      0   0  
3       0    0     0    1    0      0   0  
4       0    0     0    1    0      0   0  
...   ...  ...   ...  ...  ...    ...  ..  
1200    0    1     0    1    0      0   0  
1201    0    0     0    1    0      0   0  
1202    0    1     0    0    0      0   0  
1203    0    1     0    0    0      0   0  
1204    0    0     0    0    0      0   0  

[1205 rows x 40 columns]

In [186]:
lunch_df

중식메뉴
0        [요구르트, 쌀밥, 쇠불고기, 계란찜, 포기김치, 청포묵무침, 잡곡밥, 오징어찌개]
1     [가자미튀김, 모둠소세지구이, 마늘쫑무침, 요구르트, 배추겉절이, 쌀밥, 김치찌개,...
2         [쫄면야채무침, 치킨핑거, 견과류조림, 팽이장국, 요구르트, 포기김치, 카레덮밥]
3       [시금치나물, 쇠고기무국, 요구르트, 쌀밥, 주꾸미볶음, 포기김치, 부추전, 잡곡밥]
4        [돈육씨앗강정, 요구르트, 쌀밥, 우엉잡채, 청경채무침, 포기김치, 떡국, 잡곡밥]
...                                                 ...
1200  [생깻잎지, 오리엔탈D, 수제함박스테이크, 견과류마카로니범벅, 찰현미밥, 쌀밥, 흑...
1201  [냉이된장국, 봄동전, 수수밥, 동파육, 찰현미밥, 무생채, 파인D, 쌀밥, 청경채...
1202  [전주비빔밥, 계란파국, 자몽D, 요거닭, 약고추장, 파프리카해초무침, 포기김치, ...
1203  [봄동겉절이, 달래양념장, 전주식콩나물해장국, 돈육간장불고기, 깐풍연근, 연두부, ...
1204  [찰현미밥, 옥수수콘치즈구이, 가지고추장무침, 요구르트, 쌀밥, 귀리밥, 들깨미역국...

[1205 rows x 1 columns]

In [189]:
lunch_train = pd.concat([lunch_df,lunch_sort],axis=1)
lunch_train

중식메뉴  샐러드류  양념 및 장류  나물류  \
0        [요구르트, 쌀밥, 쇠불고기, 계란찜, 포기김치, 청포묵무침, 잡곡밥, 오징어찌개]     0        0    0   
1     [가자미튀김, 모둠소세지구이, 마늘쫑무침, 요구르트, 배추겉절이, 쌀밥, 김치찌개,...     0        0    0   
2         [쫄면야채무침, 치킨핑거, 견과류조림, 팽이장국, 요구르트, 포기김치, 카레덮밥]     0        1    0   
3       [시금치나물, 쇠고기무국, 요구르트, 쌀밥, 주꾸미볶음, 포기김치, 부추전, 잡곡밥]     0        0    1   
4        [돈육씨앗강정, 요구르트, 쌀밥, 우엉잡채, 청경채무침, 포기김치, 떡국, 잡곡밥]     0        0    0   
...                                                 ...   ...      ...  ...   
1200  [생깻잎지, 오리엔탈D, 수제함박스테이크, 견과류마카로니범벅, 찰현미밥, 쌀밥, 흑...     1        1    1   
1201  [냉이된장국, 봄동전, 수수밥, 동파육, 찰현미밥, 무생채, 파인D, 쌀밥, 청경채...     1        0    0   
1202  [전주비빔밥, 계란파국, 자몽D, 요거닭, 약고추장, 파프리카해초무침, 포기김치, ...     1        1    0   
1203  [봄동겉절이, 달래양념장, 전주식콩나물해장국, 돈육간장불고기, 깐풍연근, 연두부, ...     1        1    0   
1204  [찰현미밥, 옥수수콘치즈구이, 가지고추장무침, 요구르트, 쌀밥, 귀리밥, 들깨미역국...     1        0    0   

      소스류  두류  찜류  곡류  죽류  국탕류  ...  해조류  과일류  전류  조림류  튀김류  장아찌류  구이류  스프류  \
0       0   0   1   2   0    0  ...    0    0   0    0    0     0    1    0   
1       0   0   0   2   0    0  ...    0    0   0    0    1     0    1    0   
2       0   0   0   2   0    1  ...    0    0   0    1    1     0    0    0   
3       0   0   0   2   0    1  ...    0    0   1    0    0     0    0    0   
4       0   0   0   3   0    1  ...    0    0   0    0    1     0    0    0   
...   ...  ..  ..  ..  ..  ...  ...  ...  ...  ..  ...  ...   ...  ...  ...   
1200    1   0   0   4   1    1  ...    0    0   0    0    0     0    1    0   
1201    1   0   0   3   0    1  ...    0    1   1    1    0     0    0    0   
1202    2   0   0   0   0    1  ...    1    1   0    0    1     0    0    0   
1203    2   1   1   3   0    1  ...    2    1   0    0    1     0    1    0   
1204    1   0   0   4   0    1  ...    1    0   0    0    1     0    1    0   

      덮밥국밥류  떡류  
0         0   0  
1         0   0  
2         1   0  
3         0   0  
4         0   0  
...     ...  ..  
1200      0   0  
1201      0   0  
1202      0   0  
1203      0   0  
1204      0   0  

[1205 rows x 41 columns]

In [203]:
dinner_train = pd.concat([dinner_df,dinner_sort],axis=1)
dinner_train

석식메뉴  샐러드류  양념 및 장류  나물류  \
0            [두부조림, 쌀밥, 건파래무침, 포기김치, 육개장, 잡곡밥, 자반고등어구이]     0        0    0   
1              [유산슬, 바나나, 어묵국, 포기김치, 아삭고추무침, 양념장, 콩나물밥]     0        1    0   
2          [고기전, 청국장찌개, 새송이버섯볶음, 쌀밥, 황태양념구이, 포기김치, 잡곡밥]     0        1    0   
3              [무피클, 우동, 군고구마, 겨자장, 미니김밥, 포기김치, 멕시칸샐러드]     1        1    0   
4          [감자소세지볶음, 쌀밥, 차돌박이찌개, 닭갈비, 포기김치, 콩나물무침, 잡곡밥]     0        0    0   
...                                                 ...   ...      ...  ...   
1200  [계란후라이, 고들빼기무침, 브로콜리깨소스무침, 맛살튀김, 미니쫄우동, 김치볶음밥,...     0        0    0   
1201      [숙주나물당근무침, 삼치양념구이, 쇠고기무국, 비엔나채소볶음, 흑미밥, 포기김치]     0        0    1   
1202  [수제비국, 참나물무침, 갓김치, 수제맛쵸킹탕수육, 흑미밥, 유부채소겨자냉채, 겉절...     0        0    0   
1203    [장어강정, 깻잎쌈, 생강채, 데리야끼소스, 열무된장국, 흑미밥, 포기김치, 오이선]     0        1    2   
1204   [쑥갓나물, 양파초절임, 깍두기, (New)할라피뇨멸치주먹밥, 수제고기육전, 잔치국수]     0        0    1   

      소스류  두류  찜류  곡류  죽류  국탕류  ...  해조류  과일류  전류  조림류  튀김류  장아찌류  구이류  스프류  \
0       0   1   0   2   0    0  ...    1    0   0    1    0     0    1    0   
1       1   0   0   0   0    1  ...    0    2   0    0    0     0    0    0   
2       0   0   0   2   0    0  ...    0    0   1    0    0     0    1    0   
3       1   0   0   2   0    0  ...    0    0   0    0    0     0    1    0   
4       0   0   0   2   0    0  ...    0    0   0    0    0     0    1    0   
...   ...  ..  ..  ..  ..  ...  ...  ...  ...  ..  ...  ...   ...  ...  ...   
1200    0   0   0   2   0    0  ...    0    0   0    0    1     0    1    0   
1201    0   0   0   1   0    1  ...    0    0   0    0    0     0    1    0   
1202    0   0   0   2   0    1  ...    0    0   0    0    1     0    0    0   
1203    1   0   0   1   0    1  ...    0    0   0    0    1     0    0    0   
1204    0   0   0   1   0    0  ...    0    0   1    0    0     0    0    0   

      덮밥국밥류  떡류  
0         0   0  
1         0   0  
2         0   0  
3         0   0  
4         0   0  
...     ...  ..  
1200      0   0  
1201      0   0  
1202      0   0  
1203      0   0  
1204      0   0  

[1205 rows x 41 columns]

In [190]:
lunch_train.to_csv("data/lunch_train.csv",encoding="utf-8-sig",index=False)

In [205]:
dinner_train.to_csv("data/dinner_train.csv",encoding="utf-8-sig",index=False)